// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkz1RmI-Von60HCxon6-KCdGFa4m6p87k',
    appId: '1:133889715579:web:08bd68960577174fe1a1de',
    messagingSenderId: '133889715579',
    projectId: 'flutter-school-7f63e',
    authDomain: 'flutter-school-7f63e.firebaseapp.com',
    storageBucket: 'flutter-school-7f63e.appspot.com',
    measurementId: 'G-SJ9CRB92S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpzDKtdS2Iy_HkbLQAJLNdbiDgL7xUqmY',
    appId: '1:133889715579:android:cda3af6c6f8c59afe1a1de',
    messagingSenderId: '133889715579',
    projectId: 'flutter-school-7f63e',
    storageBucket: 'flutter-school-7f63e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-GArvV1tiRhf4whhPW9rrdaHIGv8GBV4',
    appId: '1:133889715579:ios:bd631b521da7b2c2e1a1de',
    messagingSenderId: '133889715579',
    projectId: 'flutter-school-7f63e',
    storageBucket: 'flutter-school-7f63e.appspot.com',
    iosBundleId: 'com.qwerty.flSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-GArvV1tiRhf4whhPW9rrdaHIGv8GBV4',
    appId: '1:133889715579:ios:e2771ef6b27e39d9e1a1de',
    messagingSenderId: '133889715579',
    projectId: 'flutter-school-7f63e',
    storageBucket: 'flutter-school-7f63e.appspot.com',
    iosBundleId: 'com.qwerty.flSchool.RunnerTests',
  );
}
